### ISSUE TITLE
Can't compile the workflow

### ISSUE THREAD

**Issue by nikivdev** [lox/alfred-github-jump#6]
I tried setting this workflow for local development as I wish to make some changes to it. However trying to compile the workflow, I get these errors : 

```Bash
# github.com/nikitavoloboev/alfred-testing
./login.go:54:34: not enough arguments in call to client.Users.Get
	have (string)
	want (context.Context, string)
./repos.go:115:48: not enough arguments in call to client.Repositories.List
	have (string, *"github.com/google/go-github/github".RepositoryListOptions)
	want (context.Context, string, *"github.com/google/go-github/github".RepositoryListOptions)
./repos.go:119:17: cannot use result (type []*"github.com/google/go-github/github".Repository) as type []"github.com/google/go-github/github".Repository in append
./repos.go:138:51: not enough arguments in call to client.Activity.ListStarred
	have (string, *"github.com/google/go-github/github".ActivityListStarredOptions)
	want (context.Context, string, *"github.com/google/go-github/github".ActivityListStarredOptions)

panic: exit status 2

goroutine 1 [running]:
main.run(0x13711c8, 0x2, 0xc4200ade10, 0x4, 0x4)
	/Users/nikivi/go/src/github.com/jason0x43/go-alfred/alfred/main.go:170 +0x11f
main.build()
	/Users/nikivi/go/src/github.com/jason0x43/go-alfred/alfred/main.go:251 +0x34e
main.main()
	/Users/nikivi/go/src/github.com/jason0x43/go-alfred/alfred/main.go:126 +0x6fc
```

How did you do it?

**Comment by joffotron** [comment]
Same for me. I expect the go-github dependency has changed

**Comment by joffotron** [comment]
@nikitavoloboev It had. I have a (rough) working version here: https://github.com/lox/alfred-github-jump/pull/8

**Comment by lox** [comment]
Fixed in master.
